services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_PORT}"
    volumes:
      - ./../application:/var/www/orders-api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
  php-service:
    build:
      context: ..
      dockerfile: ./application/Dockerfile
    container_name: php-container
    ports:
      - "${FPM_EXTERNAL_PORT}:${FPM_PORT}"
    volumes:
      - ./../application:/var/www/orders-api
    depends_on:
      - mysql-service
    environment:
      - APP_LANGUAGE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - YII_ENV
  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - '${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./../migrations/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./../migrations/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
